title = "Go" # Optional
description = "Template for quickly setting up Go projects" # Optional

# All configuration related to git
[git]
enabled = false

[hooks]
# Runs shell programs before the project is created
# NOTE this means before the directory is created
before = [""]

# Runs shell programs after the project is created
after = ["go mod init $name"]

[dirs]
# Creates a blank directory called src
src = []

# Creates a directory 'lib' with a subdirectory 'test'
lib = ["test"]

# Creates a subdirectory 'more_tests' under directories lib/test
# lib.test = ["more_tests"]

[files]
# The root directory is reserved for the project directory root 
root = [".env"]

# Creates 'src/main.go' and 'src/main_test.go'
src = ["main.go", "main_test.go"]

# The same dot notation can be used to create files in directories
lib.test = ["test.go"] # creates lib/test/test.go


[content]
# To add text into files the following can be used
# This only works as long as the directory and filenames match up
src."main.go" = """package main
import ""
func main() {

}
"""

# Will write contents in to 'Project/.env'
root.".env" = ".secret_keys/"
